theme: minimal
title: CSCE 5612 Documentation Website
description: This website is created by Linto Thomas for course CSCE 5612 Embedded Hardware/Software Design Spring 2025 documentation of the lab and project work.
